# Generated by Django 4.2.1 on 2023-09-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_useraccount_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
