# Generated by Django 4.2.1 on 2023-09-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraccount_is_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_otp',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
