# Generated by Django 4.2.1 on 2023-11-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_useraccount_firstname_useraccount_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
